"""
Django settings for mateapp project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()

# Read environment variables from a .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'unfold',
]

INSTALLED_APPS += [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_cron',
]

INSTALLED_APPS += [
    'users',
    'logger',
]

AUTH_USER_MODEL = "users.CustomUser"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mateapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mateapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'backend/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static_base'),)
STATIC_ROOT = (os.path.join(BASE_DIR, 'static'))

MEDIA_URL = 'backend/files/'
MEDIA_ROOT = (os.path.join(BASE_DIR, 'files'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": 'MateApp',
    "SITE_HEADER": 'MateApp',
    "COLORS": {
    "primary": {
        "50": "233 246 235",  
        "100": "219 240 222", 
        "200": "197 231 201", 
        "300": "173 222 179", 
        "400": "101 205 124", 
        "500": "40 167 69",
        "600": "36 150 62",
        "700": "30 125 52",
        "800": "23 97 42",
        "900": "16 68 32",
        "950": "8 34 17" 
        },
    },
}

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

# Registration Settings

# Enables Self Registration
REGISTRATION_SELF_ENABLE = True
# If true, new users remain INACTIVE until manually activated by the administrator.
REGISTRATION_PARKING = False
#To restrict new user registration to a mail domain use '@domain.com', else use '@'.
REGISTRATION_DOMAIN = env.str('REGISTRATION_DOMAIN', default='@')
# User Limit
USER_LIMIT = 0
VERIFIED_REGISTRATION_REDIRECT="/"

LOGDIR = (os.path.join(BASE_DIR, 'log'))
LOGFILE = f'{LOGDIR}/mateapp.log'
LOG_RETENTION_DAYS = 30
FILE_LOGLEVEL = 'DEBUG'
DB_LOGLEVEL= 'INFO'
DJANGO_CRON_DELETE_LOGS_OLDER_THAN = 30

# SMTP Backend Settings

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env.str('EMAIL_HOST', default='')
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = 587
EMAIL_USE_TLS = True


DEFAULT_FROM_EMAIL = 'MateApp Administrator <no-reply@mateapp.ar>'

# Password reset Settings

PASSWORD_RESET_TIMEOUT = 14400

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Django Cron Settings

CRON_CLASSES = [
    'logger.crons.RemoveOldLogs'
]

DJANGO_CRON_LOCK_BACKEND = 'django_cron.backends.lock.database.DatabaseLock'